# Aliases I use contantly
alias "${CMDLEADER}g"='git'
alias "${CMDLEADER}ga"='git add'
alias "${CMDLEADER}gap"='git add --patch'
alias "${CMDLEADER}gaa"="git status -s | egrep "^ +M"| awk '{print $2}' | xargs git add"
alias "${CMDLEADER}gs"='git status'
alias "${CMDLEADER}gup"='git pull --rebase'
alias "${CMDLEADER}gups"='git stash && git pull --rebase && git stash apply'
alias "${CMDLEADER}gwc"='git whatchanged -p --abbrev-commit --pretty=medium'
alias "${CMDLEADER}greset"='git checkout --'
alias "${CMDLEADER}gsaveme"='git reset --hard orig_head'
alias "${CMDLEADER}gsetupstream"='git branch --set-upstream-to=origin/$(current_branch) $(current_branch)'
alias "${CMDLEADER}gb"='git branch'
alias "${CMDLEADER}gc"='git commit -v'
alias "${CMDLEADER}gca"='git commit -v -a'
alias "${CMDLEADER}gcamend"='git commit --amend'
alias "${CMDLEADER}gcamendr"='git commit --amend --reuse-message=HEAD'
alias "${CMDLEADER}gco"='git checkout'
alias "${CMDLEADER}gd"='git diff'
alias "${CMDLEADER}ggpush"='git push origin $(current_branch)'
alias "${CMDLEADER}ggpushf"='git push origin $(current_branch) --force-with-lease'
alias "${CMDLEADER}gremoveuntracked"='rm -rf `git status --porcelain | sed -e -e"s/\?\? / /" | tr -d '\\n'`'
alias "${CMDLEADER}gfetch"='git fetch'

# Ones I use less frequently
alias "${CMDLEADER}gcl"='git config --list'
alias "${CMDLEADER}gba"='git branch -a'
alias "${CMDLEADER}gcm"='git checkout master'
alias "${CMDLEADER}gcount"='git shortlog -sn'
alias "${CMDLEADER}gcp"='git cherry-pick'
alias "${CMDLEADER}gf"='git ls-files | grep'
alias "${CMDLEADER}ggpnp"='git pull --rebase origin $(current_branch) && git push origin $(current_branch)'
alias "${CMDLEADER}ggpull"='git pull --rebase origin $(current_branch)'
alias "${CMDLEADER}glg"='git log --pretty=format:"%h %s" --graph'
alias "${CMDLEADER}glgg"='git log --graph --max-count=5'
alias "${CMDLEADER}glgga"='git log --graph --decorate --all'
alias "${CMDLEADER}gl"='git log'
alias "${CMDLEADER}gm"='git merge'
alias "${CMDLEADER}gp"='git push'
alias "${CMDLEADER}gpoat"='git push origin --all && git push origin --tags'
alias "${CMDLEADER}gr"='git remote'
alias "${CMDLEADER}grh"='git reset head'
alias "${CMDLEADER}grhh"='git reset head --hard'
alias "${CMDLEADER}gri"='git rebase -i --preserve-merges --autosquash'
alias "${CMDLEADER}grmv"='git remote rename'
alias "${CMDLEADER}grrm"='git remote remove'
alias "${CMDLEADER}grset"='git remote set-url'
alias "${CMDLEADER}grt"='cd $(git rev-parse --show-toplevel || echo ".")'
alias "${CMDLEADER}grup"='git remote update'
alias "${CMDLEADER}grv"='git remote -v'
alias "${CMDLEADER}gss"='git status -s'
